AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: A starter AWS Lambda function.
Resources:
  xmlchecker:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: xmlchecker::xmlchecker.Function::FunctionHandler
      Runtime: dotnetcore2.1
      CodeUri: "bin/release/netcoreapp2.1/publish"
      MemorySize: 1024
      Timeout: 3
      Role: 'arn:aws:iam::573575823092:role/lambdafullaccess'
      Tracing: Active
      Environment:
        Variables:
            BUCKET_NAME: siri-lambda-test
            SCHEMA_FILENAME: books.xsd
            SCHEMA: false
