AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: A starter AWS Lambda function.
Resources:
  xmlcheckerc:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: xmlchecker::xmlchecker.Function::FunctionHandler
      Runtime: dotnetcore2.1
      CodeUri: "bin/release/netcoreapp2.1/publish"
      MemorySize: 1024
      Timeout: 3
      Role: 'arn:aws:iam::573575823092:role/lambdafullaccess'
      Tracing: Active
      Environment:
        Variables:
            BUCKET_NAME: siri-lambda-test
            SCHEMA_FILENAME: books.xsd
            SCHEMA: false
     AutoPublishAlias: live
     DeploymentPreference:
       Type: Canary10Percent10Minutes 
       Alarms:
         # A list of alarms that you want to monitor
         - !Ref AliasErrorMetricGreaterThanZeroAlarm
         - !Ref LatestVersionErrorMetricGreaterThanZeroAlarm
       Hooks:
         # Validation Lambda functions that are run before & after traffic shifting
         PreTraffic: !Ref PreTrafficLambdaFunction
         PostTraffic: !Ref PostTrafficLambdaFunction